apiVersion: v1
kind: Service
metadata:
  annotations:
  name: secc-ui-service
  namespace: "9990227"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: secc-ui
  type: ClusterIP
